### ISSUE TITLE
Music fragments are missing

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#10]
Please add the following music fragments: 
- [x] Error
- [x] Complete
- [x] Background
- [x] Road
- [x] Menu
- [x] Construction
- [x] Button
- [x] Reset
- [x] Level Select
- [ ] Loading screen (?)
- [ ] Back button on level select
- [ ] Menu buttons

**Comment by carlo-theunissen** [comment]
@Dyhart  I have change the audio api. 
In the previous code you had to use the getAudio(name) function which returned an audio clip. Now you have a playAudio(name) function what just plays the audio.

This change has been made because the user has the option to disable the audio #12 . If the user disables the audio, the playAudio function doesn't do anything. 

See the commit at: 591c584cb5c711cf63afaf0a3d11a64c1e0fc278

**Comment by WouterStrangeDuck** [comment]
All the Audio has been added except the road, i dont really know what kind of sound we need for this??? The sound effects can be found in the drive.

**Comment by Dyhart** [comment]
I've added a couple of sounds. a0fb3445cb902f3362b037bc2c29f6247907c9c2

**Comment by KLiebregts** [comment]
Wrong sound under placement roads.

**Comment by Dyhart** [comment]
Fixed the road placement sounds

**Comment by carlo-theunissen** [comment]
While holding the "reset button" the audio is played over and over. This causes a weird sound.

**Comment by carlo-theunissen** [comment]
There is no sound in the level select #12  and in the loading screen #9
