### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#16]
The game doesn't cache anything! 
- [x] Mouse.cs, check if the mouse really has changed 
- [x] Block.cs, a lot!
- [x] Level.cs, the pathfinding result
- [x] PieceFactory.cs, a lot!

**Comment by carlo-theunissen** [comment]
@KLiebregts I have had to refactor a lot of code, could you please test the closed bug tickets? Just to make sure that there aren't any bugs recreated.

**Comment by Dyhart** [comment]
The closed tickets have been tested and it seems to be just fine.
