### ISSUE TITLE
Creating waves with the road blocks

### ISSUE THREAD

**Issue by Dyhart** [carloboy7/UrbanRoad#18]
When the level is finished you can keep replacing blocks, and when you do the road pieces start laying down even though the road is already finished. When you do this repeatedly it creates waves in the road.

**Comment by carlo-theunissen** [comment]
The level gets locked if the road is laid. I've also added an option to remove the road, this is simply the reset button. If that happens, the lock will be removed.

**Comment by WouterStrangeDuck** [comment]
Tested, works awesome
