### ISSUE TITLE
Finish with unused blocks

### ISSUE THREAD

**Issue by Dyhart** [carloboy7/UrbanRoad#22]
The roadpieces are being placed even though there are still a few open spots on the map. Also not every block is used (1 in this case).

![e857f6ee13b6e241af4bd6b4e8949e24](https://cloud.githubusercontent.com/assets/1445830/14144157/e63610de-f68e-11e5-9f4a-876ed105bb8d.png)

**Comment by carlo-theunissen** [comment]
@Dyhart  Could you please test if the game checks if all the pieces are placed? The "empty" spots problem is covered in ticket #5
