### ISSUE TITLE
Grid needs a texture

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#24]
<img width="483" alt="screen shot 2016-03-31 at 11 00 42" src="https://cloud.githubusercontent.com/assets/7584025/14170805/e2e07310-f72f-11e5-8e4f-6abed34bba30.png">
The grid looks really ugly. Where is the texture for that?

**Comment by WouterStrangeDuck** [comment]
It has a texture now, im going to make it a bit more fancy
