### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#27]
We need some awesome popups. These popups give the user some advise and explain why curtain actions happen. 

**The popups we need (in my opinion)**
- When the player finishes a level, this needs to be celebrated. I has to give the feeling like you've done something useful with your live. 
- When the player places all the blocks in the level, but they were placed invalid. This popup in only show  to the player once each level. This popup needs to have an educative feeling. Please don't intent the user as stupid. 

**An quick reminder**
The level is invalid when:
- There is no free place from the start to the finish.
- If the "free place" is more than 1 tile wide
- If there are empty spots in the game, even through the road is placed.

**Comment by carlo-theunissen** [comment]
@wouterku , @thomasfranken you had some work for this right?

**Comment by carlo-theunissen** [comment]
Please, take also a note at #25 . The "succes" popup needs to have a "next level" button too.

**Comment by carlo-theunissen** [comment]
![unknown](https://cloud.githubusercontent.com/assets/7584025/14226668/64d2fa6e-f8e8-11e5-8c80-8307b9f5ad0d.jpeg)

**Comment by carlo-theunissen** [comment]
Could the succes popup be tested?

**Comment by WouterStrangeDuck** [comment]
Tested and works fine. We could add an animation to make it more fancy

**Comment by WouterStrangeDuck** [comment]
The other popups can be implemented to, they are already in unity

**Comment by carlo-theunissen** [comment]
The fail popus has been added. However, because of the missing assets does it look really weird.

**Comment by carlo-theunissen** [comment]
The fail popup has been updated. It has the correct images now
