### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#34]
Why is the credits scene still blank?

**Comment by WouterStrangeDuck** [comment]
was going to make this in the evening. There is alot of information that has to get in here, thomas and i will be looking into this on monday.

**Comment by Dyhart** [comment]
Made a sample text move up automatically and when the entire text has been shown the scene automatically changes back to the main menu..

**Comment by carlo-theunissen** [comment]
Oh awesome!
