### ISSUE TITLE
Check for holes

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#5]
The game doesn't check for empty holes in the game. 
Take for example the attachment, the road is valid, but the upper right corner is still empty. So this level is _not_ completed.

<img width="100" alt="invalid" src="https://cloud.githubusercontent.com/assets/7584025/13847040/6be2a0c4-ec4b-11e5-89d9-e146872c46f6.png">

**Comment by KLiebregts** [comment]
array form pathfining must be aslong as there are road tiles available.

**Comment by carlo-theunissen** [comment]
@thomasfranken how do we indicate to the user that the level is not valid although it has a valid road? Are we going to display some 3d markers on the invalid spots or just a pop-up?

**Comment by KLiebregts** [comment]
![](https://i.gyazo.com/ea5b1bc0f53b4680bac68b9d39fe339e.png)

Zoals je hier kunt zien hebben we 2 holes
