### ISSUE TITLE
Road Placement

### ISSUE THREAD

**Issue by KLiebregts** [carloboy7/UrbanRoad#7]
Making the road placer place the right blocks including animation.

**Comment by wouterku** [comment]
![output_dhgxbj](https://cloud.githubusercontent.com/assets/10127018/13914123/c7d3d016-ef4c-11e5-9bdb-4d5a8c0de56b.gif)

**Comment by WouterStrangeDuck** [comment]
![output_vnjkdh](https://cloud.githubusercontent.com/assets/10127018/13914158/f0029478-ef4c-11e5-9ed3-e457ed7177f6.gif)

**Comment by carlo-theunissen** [comment]
@wouterku the block 2's pivot point is not set correctly. 
@KLiebregts there are some problems with the calculation of the road corners. 

<img width="352" alt="screen shot 2016-03-21 at 21 39 46" src="https://cloud.githubusercontent.com/assets/7584025/13933545/f8d55354-efad-11e5-8f3d-034c6bc2d061.png">
<img width="260" alt="screen shot 2016-03-21 at 21 39 51" src="https://cloud.githubusercontent.com/assets/7584025/13933544/f8a0d9b2-efad-11e5-9c10-1fe9643c6898.png">

**Comment by carlo-theunissen** [comment]
@KLiebregts I've added the road placement animation. I have also edited the RoadPiece script, you have to set the "direction" property so the animation scripts knows from which side the road has to be animated. 

Also @Dyhart I've added some comments in the RoadPlaces script for you :) #10

**Comment by Dyhart** [comment]
CHECK LEVEL 4 BITCH

**Comment by KLiebregts** [comment]
![](https://i.gyazo.com/730f291d1f83c27db43475a197333667.png)
hier het probleem er zijn 2 stukken road omgedraaid.
In dit geval piece 5 en 6 

Ik ga er vanuit dat ze van links naar rechts zijn geplaatst
