### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#8]
If the user places a block on the grid and leaves the app, that position is not saved.
This has to change. 

Every time the grid changes, the state of the game has to be saved on the device. Also, if a user completes the level his scores has to be saved.

**Comment by carlo-theunissen** [comment]
@KLiebregts What would be the best idea for saving completed levels? We can still save the positions of the objects, but we can also remove the positions. In that case, the user doesn't has a clue what his previous solution was

**Comment by KLiebregts** [comment]
@carloboy7 
The last placed block must be found back where it was leftoff.

Incase of a big level it will be very anoying if you almost completed it and you come back and your progres is gone.

**Comment by carlo-theunissen** [comment]
@KLiebregts Yeah I get that, but my questions is regards the completion of a level.
We store which levels the user has completed, but do we sill need to save the block's position if the level is done?

**Comment by KLiebregts** [comment]
yes, but if they reset it the solution won't show again of how you finished it the last time.

so how you leave it is how you find it.
So if you wanne show off how you completed it you can as long as you don't reset the level.

**Comment by carlo-theunissen** [comment]
Oke, I get it! Thanks

**Comment by carlo-theunissen** [comment]
@KLiebregts The positions of blocks get saved now. Could you please test this? Try to break it so I know where the bugs are haha.
